### PR TITLE
Fix sourcemap support

### LINKED ISSUE #21: source map not work
## Current Behavior

1. isbanbul plugin print error on configuring the source map
```text
TypeError: instrumenter.lastSourceMap(...).toJSON is not a function
    at Object.transform (/test/node_modules/rollup-plugin-istanbul/dist/rollup-plugin-istanbul.cjs.js:30:58)
    at Promise.resolve.then (/test/node_modules/rollup/dist/rollup.js:15344:25)
```
2.  the `souceMap` option not work, need to config `instrumenterConfig.produceSourceMap`

## Steps to Reproduce

- isbanbul plugin plugin configuration
```js
istanbul({
	exclude: ['test/*'],
	sourceMap: true,
	instrumenterConfig: {
		produceSourceMap: true
	}
})
```

## Context (Environment)

 Windows 10, node v10.15.3

## Possible Implementation

1. [instrumenter.lastSourceMap](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-instrument/api.md#lastsourcemap) returns (null | Object) the source map object.
2. set [instrumenterConfig.produceSourceMap](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-instrument/api.md#parameters-1) on `ops.sourceMap` enabled

### PR DESCRIPTION
**Pull request by billowz**
## Description

* fix sourcemap
* update dependencies
* update readme.md

## Related Issue

closes #21 

## Motivation and Context

the sourceMap option not work (#21)

## How Has This Been Tested?

I have add a test to check the generated source map from rollup

### CODE REVIEW

**Comment by benmccann** [comment]
@artberri any change you'd be able to take a look at this PR?

**Comment by doppelganger9** [comment]
Hi,

This PR + a new published NPM version will help solving - in a clean way - this issue on another repository : https://github.com/bahmutov/coverage-example-svelte/issues/1

In the meantime, we'll reference the `rc` branch from @billowz forked repo.
`npm install --save-dev https://github.com/billowz/rollup-plugin-istanbul#rc`

**Comment by niksy** [comment]
What is the status of this PR? Can we get this merged?

**Comment by artberri** [comment]
I was a bit 'out' of this package, I'll try to review this during this week if possible.

**Comment by artberri** [comment]
Hi @billowz the new version [3.0.0](https://github.com/artberri/rollup-plugin-istanbul/releases/tag/v3.0.0) that I've already published in the [npm registry](https://www.npmjs.com/package/rollup-plugin-istanbul) should fix the bug.

The PR has been automatically closed because I changed the default branch name from `master` to `main`. Anyway, I didn't want to merge it because it was a bit outdated (my fault, of course). I don't think the `extensions` option is needed neither.

So, I've finally coded the fix myself based on your work. THANK YOU VERY MUCH FOR YOUR TIME.

/cc @niksy

**Pull request closed without merging**
